# Generated by Django 4.0.3 on 2022-04-26 04:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drug',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=50)),
                ('synonym', models.CharField(default='NA', max_length=50)),
                ('abbreviation', models.CharField(default='NA', max_length=50)),
                ('drugclass', models.CharField(default='NA', max_length=250)),
                ('description', models.CharField(default='NA', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=250)),
                ('region', models.CharField(default='NA', max_length=250)),
                ('age', models.CharField(default='NA', max_length=250)),
                ('gender', models.CharField(default='NA', max_length=250)),
                ('nationality', models.CharField(default='NA', max_length=250)),
                ('religion', models.CharField(default='NA', max_length=250)),
                ('employment', models.CharField(default='NA', max_length=250)),
                ('tribe', models.CharField(default='NA', max_length=250)),
                ('education', models.CharField(default='NA', max_length=250)),
                ('maritalStatus', models.CharField(default='NA', max_length=250)),
                ('district', models.CharField(default='NA', max_length=250)),
                ('county', models.CharField(default='NA', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=250)),
                ('description', models.CharField(default='NA', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='regimen',
            fields=[
                ('regimen_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug1', models.CharField(default='NA', max_length=50)),
                ('drug2', models.CharField(default='NA', max_length=50)),
                ('drug3', models.CharField(default='NA', max_length=50)),
                ('abbreviation', models.CharField(default='NA', max_length=10)),
                ('description', models.CharField(default='NA', max_length=250)),
                ('treatmentLine', models.CharField(default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sample',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=50)),
                ('specimen', models.CharField(default='NA', max_length=50)),
                ('laboratory', models.CharField(default='NA', max_length=50)),
                ('labtech', models.CharField(default='NA', max_length=250)),
                ('volume', models.IntegerField(default=0)),
                ('plasma', models.IntegerField(default=0)),
                ('cd4', models.IntegerField(default=0)),
                ('viralLoad', models.IntegerField(default=0)),
                ('tube', models.IntegerField(default=0)),
                ('btebb', models.DateField(default=django.utils.timezone.now)),
                ('dopsep', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='sequence',
            fields=[
                ('sequence_id', models.AutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(default='NA', max_length=50)),
                ('species', models.CharField(default='HIV', max_length=50)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(default=django.utils.timezone.now)),
                ('host', models.CharField(default='Human', max_length=50)),
                ('gene', models.CharField(default='NA', max_length=10)),
                ('subtype', models.CharField(default='NA', max_length=10)),
                ('sequencing_platform', models.CharField(default='NA', max_length=50)),
                ('residues', models.CharField(default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFastq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastqfiles', models.FileField(blank=True, null=True, upload_to='Fastq/')),
            ],
        ),
        migrations.CreateModel(
            name='sampleSequence',
            fields=[
                ('sample_sequence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sampleID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hivdb.sample')),
                ('sequenceID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hivdb.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='participantSample',
            fields=[
                ('participant_sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('participantID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hivdb.participant')),
                ('sampleID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hivdb.sample')),
            ],
        ),
        migrations.CreateModel(
            name='participantRegimen',
            fields=[
                ('participant_regimen_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('participantID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hivdb.participant')),
                ('regimenID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hivdb.regimen')),
            ],
        ),
    ]
